INSERT INTO applicant VALUES (10005,'High School','Germany','Technical University Munich');
INSERT INTO applicant VALUES (10006,'Undergraduate','Canada','University of Toronto');
INSERT INTO applicant VALUES (10011,'Undergraduate','Singapore','Nanyag Technological University');
INSERT INTO applicant VALUES (10024,'Graduate','Germany','Frele University of Berlin');
INSERT INTO applicant VALUES (10025,'High School','Singapore','Nanyag Technological University');
INSERT INTO applicant VALUES (10026,'Undergraduate','Germany','Frele University of Berlin');
INSERT INTO applicant VALUES (10039,'Graduate','Singapore','Nanyag Technological University');
INSERT INTO applicant VALUES (10040,'Undergraduate','Canada','University of Toronto');
INSERT INTO applicant VALUES (10042,'Graduate','Italy','University of Bologna');
INSERT INTO applicant VALUES (10043,'Undergraduate','Canada','University of Toronto');
INSERT INTO applicant VALUES (10044,'High School','Germany','Technical University Munich');
INSERT INTO applicant VALUES (10045,'Undergraduate','Canada','University of British Columbia');
INSERT INTO applicant VALUES (10046,'Graduate','Germany','Frele University of Berlin');
INSERT INTO applicant VALUES (10017,'Graduate','USA','The University of Texas at Arlington');
INSERT INTO applicant VALUES (10013,'High School','Germany','Frele University of Berlin');
INSERT INTO applicant VALUES (10041,'Graduate','Italy','University of Bologna');
INSERT INTO applicant VALUES (10009,'Graduate','Germany','Technical University of Munich');
INSERT INTO applicant VALUES (10018,'Graduate','USA','The University of Texas at Arlington');
INSERT INTO applicant VALUES (10029,'Graduate','United Kingdom','Imperial College London');
INSERT INTO applicant VALUES (10001,'Graduate','Bangladesh','University of Dhaka');
INSERT INTO applicant VALUES (10004,'High School','United Kingdom','Imperial College London');
INSERT INTO applicant VALUES (10034,'Graduate','USA','The University of Texas at Arlington');
INSERT INTO applicant VALUES (10037,'Graduate','Singapore','Nanyag Technological University');